# Generated by Django 4.2.4 on 2024-04-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_username', models.CharField(max_length=20)),
                ('user_type', models.IntegerField()),
            ],
        ),
    ]
