# Generated by Django 4.2.4 on 2024-04-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_ids_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ids',
            name='user_type',
            field=models.CharField(max_length=1),
        ),
    ]
