# Generated by Django 4.2.4 on 2024-04-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_ids_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ids',
            name='user_id',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='ids',
            name='user_username',
            field=models.CharField(max_length=30),
        ),
    ]
